dns:
    server: 8.8.8.8
    cached: true
twitter:
    consumer_key: [consumer_key]
    consumer_secret: [consumer_secret]
    access_token: [access_token]
    access_token_secret: [access_token_secret]
    search:
        - "#[hash tag]"

